### ISSUE TITLE
dependency issue 

### ISSUE THREAD

**Issue by jskye** [vladimir-vovk/react-native-sample-profile#10]
has a dependency issue with launching on physical device via QR code. 
requires expo update to version 39 which then causes dependency problem with a library `react-native-community/async-storage` which now lives at `react-native-async-storage/async-storage`. trying to install that library gets it to launch but without displaying the native code properly.

**Comment by vladimir-vovk** [comment]
Hi @jskye !
Thank you for your message. This code is 2 years old so it's outdated now. 

Issues I see:
- old React Navigation (API were changed)
- outdated libs: Expo Permissions, react-hook-forms, etc
- I would prefer to use React Context now instead of MobX
- use Functional Components and hooks

I would use it more as a reference. And rewrite this example from scratch. 🤓
